name:                advent-of-code-ocr
version:             0.1.2.0
github:              "mstksg/advent-of-code-ocr"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "2020 Justin Le"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Parse Advent of Code ASCII art letters
category:            Text

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: |
  "OCR" letter recognition for <https://adventofcode.com Advent of Code>
  puzzles, compatible with all puzzles from 2015 to 2019.  Also comes with a
  handy command line utility to parse the ASCII art directly from stdin.


ghc-options:
- -Wall
- -Werror=incomplete-patterns
- -Wredundant-constraints

dependencies:
- base >= 4.7 && < 5
- containers
- heredoc
- th-compat
- th-lift-instances
- th-lift
- data-default-class
- template-haskell

library:
  source-dirs: src
  other-modules:
  - Advent.OCR.LetterMap

executables:
  advent-of-code-ocr:
    main:                ocr.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code-ocr
    - optparse-applicative

tests:
  advent-of-code-ocr-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code-ocr
    - hspec

benchmarks:
  advent-of-code-ocr-bench:
    main: bench.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - advent-of-code-ocr
    - criterion
